# Generated by Django 4.2.6 on 2023-10-24 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=250)),
                ('no_street', models.IntegerField()),
                ('country', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='home',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='persons.home'),
        ),
    ]
